/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Wizard = React.memo(function Wizard(props) {
  const { scene } = useGLTF("/models/fully_rigged_witch.glb");
  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.position.y = -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      position={[0, - 0.3, 0]}  // Adjusted to move the model up
      scale={[1.2, 1.2, 1.2]}
      rotation={[0, Math.PI / 4, 0]}
    >
      <primitive object={scene} />
    </group>
  );
});

export default Wizard;
useGLTF.preload("/models/fully_rigged_witch.glb");